FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt update
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y sudo git unzip wget vim apt-utils
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y cmake make build-essential
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y libgl1-mesa-dev libglfw3-dev libssl-dev libopencv-contrib-dev libopencv-dev
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y python3-pip python3-tk python3-dev 
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y tigervnc-standalone-server openbox

# Set BASH as the default shell
RUN echo "dash dash/sh boolean false" | debconf-set-selections 
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND dpkg-reconfigure dash

# Install other dependencies
COPY /gui-testing/*.sh /scripts/
COPY /test-harness/*.sh /scripts/
RUN chmod -R +x scripts
RUN /scripts/install_testdeps.sh 
RUN /scripts/install_nebula.sh
RUN /scripts/install_telemetry.sh

# Cleanup
RUN apt-get clean