FROM ubuntu:20.04

MAINTAINER Travis Collins <travis.collins@analog.com>

ENV XLNX_INSTALL_LOCATION=/opt/Xilinx
ENV DEBIAN_FRONTEND=noninteractive

RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt clean
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt autoclean
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt update
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y libpng-dev libfreetype6-dev libblas-dev liblapack-dev gfortran build-essential xorg
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y openjdk-8-jre openjdk-8-jdk libgtk2.0-0 libxss1 libxt6 zip unzip curl wget tar git xvfb
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y fakeroot libncurses5-dev libssl-dev ccache dfu-util u-boot-tools device-tree-compiler
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y libssl-dev mtools bc python python3 cpio zip unzip rsync file wget libicu66 libicu-dev screen
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y python3-pip iputils-ping sudo net-tools iproute2 bison flex libtinfo5
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND dpkg --add-architecture i386
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y lib32stdc++6
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y sudo

# MATLAB dependencies
COPY base-dependencies.txt /tmp/base-dependencies.txt
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get install --no-install-recommends -y `cat /tmp/base-dependencies.txt` \
    && apt-get clean && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

# Install patched glibc
RUN wget https://github.com/mathworks/build-glibc-bz-19329-patch/releases/download/ubuntu-focal/all-packages.tar.gz
RUN tar xf all-packages.tar.gz
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND dpkg -i *.deb || true

# Set BASH as the default shell
RUN echo "dash dash/sh boolean false" | debconf-set-selections
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND dpkg-reconfigure dash

# Cleanup
RUN apt-get clean

# Add HSP
# COPY mlhsp /mlhsp
COPY HSPs /HSPs

# Add MATLAB config
#ADD .matlab /root/.matlab
ADD .matlab /home/tcollins/.matlab

# Entrypoint for runtime pre-processing
#RUN mkdir /work

RUN useradd -u 57532 --create-home --shell /bin/bash -G sudo tcollins
RUN groupadd -g 17140 romlx
RUN usermod -aG romlx tcollins
RUN echo 'tcollins:tcollins' | chpasswd
RUN chown -R tcollins:tcollins /home/tcollins
RUN chown -R tcollins:tcollins /HSPs

USER tcollins
WORKDIR /home/tcollins
#RUN chmod 777 /work
