FROM python:3.9

ENV DEBIAN_FRONTEND=noninteractive

RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt update
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND apt-get install -y wget sudo
RUN DEBIAN_FRONTEND=$DEBIAN_FRONTEND sudo apt install -y python3-tk

COPY all_python_versions.sh /tmp/all_python_versions.sh
RUN chmod +x /tmp/all_python_versions.sh
RUN /tmp/all_python_versions.sh