FROM centos:7

# RUN yum clean all && rm -r /var/cache/yum  && yum upgrade -y && yum update -y

RUN yum group install -y "Development Tools"
RUN yum install -y gcc gcc-c++ git wget

RUN yum install -y flex bison libxml2-devel

RUN yum install -y libaio-devel libusb-devel.x86_64 avahi-devel.x86_64 libzstd-devel.x86_64 rpm rpm-build

RUN yum install -y doxygen graphviz man2html

RUN yum install -y python3-pip python3-setuptools
RUN pip3 install --upgrade pip
RUN pip3 install sphinx sphinx_rtd_theme furo

RUN wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2.tar.gz
RUN tar xf cmake-3.23.2.tar.gz
WORKDIR cmake-3.23.2
RUN ./bootstrap
RUN make -j$(nproc)
RUN make install
RUN ldconfig
WORKDIR /

RUN git clone https://github.com/pcercuei/libini.git
RUN cd libini && mkdir build && cd build && cmake ../ && make && make install && ldconfig

# Cleanup
RUN yum clean all
