FROM fedora:34

RUN dnf clean all && rm -r /var/cache/dnf  && dnf upgrade -y && dnf update -y

RUN dnf install -y cmake gcc git

RUN dnf install -y flex bison libxml2-devel

RUN dnf install -y libaio-devel libusb-devel.x86_64 avahi-devel.x86_64 libzstd-devel.x86_64

RUN dnf install -y doxygen graphviz

RUN dnf install -y python3-pip python3-setuptools
RUN pip3 install --upgrade pip
RUN pip3 install sphinx sphinx_rtd_theme

RUN git clone https://github.com/pcercuei/libini.git
RUN cd libini && mkdir build && cd build && cmake ../ && make && make install && ldconfig

# Cleanup
RUN dnf clean all
