name: ci-build-deploy

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["hdl", "sw", "ubuntu-18.04", "ubuntu-20.04"]
        include:
        - project: "hdl"
          Dockerfile: "Dockerfile-hdl"
          tag_root: "hdl-ci"
        - project: "sw"
          Dockerfile: "Dockerfile-sw"
          tag_root: "sw-ci"
        - project: "libiio-ubuntu-18.04"
          Dockerfile: "libiio/Dockerfile-ubuntu-18.04"
          tag_root: "libiio_ubuntu_18_04-ci"
        - project: "libiio-ubuntu-20.04"
          Dockerfile: "libiio/Dockerfile-ubuntu-20.04"
          tag_root: "libiio_ubuntu_20_04-ci"
        - project: "libiio-fedora-34"
          Dockerfile: "libiio/Dockerfile-fedora-34"
          tag_root: "libiio_fedora_34-ci"

    steps:
      -
        name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.project.Dockerfile }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: tfcollins/${{ matrix.project.tag_root }}:latest