name: ci-dev

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        filename:
          [
            "Dockerfile-hdl",
            "Dockerfile-sw",
            "libiio/Dockerfile-ubuntu-18.04",
            "libiio/Dockerfile-ubuntu-20.04",
            "libiio/Dockerfile-fedora-34",
          ]
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.filename }}
          push: false
