name: Test-Not-Push

on:
  push:
    branches:
      - 'dev'

jobs:
  docker:

    strategy:
      matrix:
        file: [ hdl, sw ]

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        #      -
        #        name: Build only
        #        uses: docker/build-push-action@v2
        #        with:
        #          context: .
        #          push: false
        #          file: Dockerfile-${{ matrix.file }}
        #          tags: ${{ matrix.file }}-test
      -
        name: Build container
        run: docker build . --file Dockerfile-${{ matrix.file }} --tag ${{ matrix.file }}-test
      -
        name: Test container
        run: |
                docker run ${{ matrix.file }}-test /bin/bash -c test_build.sh


